### ISSUE TITLE
consolidate code base, update dependencies

### ISSUE THREAD

**Issue by tmfrnz** [impactoss/impactoss-tasks#30]
#### dependencies

- [ ] update dependencies @parndt, also see https://github.com/impactoss/impactoss-server/issues/366

#### bring in enhancements from derivatives

- [x] Track updates to relationships in all related tables (https://github.com/dumparkltd/advocacy-tracker-server/issues/46)  @parndt - see https://github.com/impactoss/impactoss-server/issues/362

#### other

- [ ]  clean up code base, remove unused code and tests @parndt - see https://github.com/impactoss/impactoss-server/issues/363

---

#### dependencies

- [ ] update dependencies 
- [x] consider use of grommet JS components
- [x] consider dropping immutable-js -- not for now
- [x] consider replacing react-redux-form -- not for now

#### branding/theme

- [ ] simplify theming?
 
#### bring in developments from derivatives

- [ ] improved log in workflow (Advocacy Tracker) @vbojilova 
- [x] improved markdown editor (Advocacy Tracker) @vbojilova -- https://github.com/impactoss/impactoss-client/issues/522
- [ ] improved data import, allowing import of selected relationships (Advocacy Tracker)

#### refactoring & clean up

- [ ] clean up hard-coded text bits @vbojilova 
- [x] consider replacing classes with functional components -- no
- [x] consider refactoring react-intl to one level (allowing for automatic extraction)
- [ ] consider improving client configuration (increasing flexibility)

--- 

### General/both

- [ ] consider lazy-loading strategies
- [ ] consider storing client config in database
